#!/bin/sh

#     This script is part of Netkit, a network emulation environment based on
#     the integration of several existing pieces of software.
#     For more information: http://www.netkit.org/
#
#     Copyright (C) 2015
#         Massimo Rimondini (rimondin@ing.uniroma3.it)
#     Computer Networks Research Group, Roma Tre University
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, version 3 of the License.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /opt/netkit-setup/utils.sh

becho "Configuring installed packages"

# Disable boot-time services
while read SERVICENAME; do
systemctl disable $SERVICENAME
done << EOF
apache2
pdns
bind9
dhcpcd
freeradius
inetd
nfs-common
nmbd
openvswitch-switch
rinetd
rpcbind
rsyslog
smbd
smcroute
snmpd
squid
ssh
strongswan
uml-utilities
dnsmasq
ebtables
ipvsadm
isc-dhcp-server
mrd6
nfs-kernel-server
openvpn
pdnsd
proftpd
quagga
radvd
samba-ad-dc
setkey
shorewall
shorewall6
snort
xorp
uuidd
swap.target
cryptsetup.target
graphical.target
mail-transport-agent.target
nss-lookup.target
exim4
pppd-dns
EOF
