#!/bin/sh

#     This script is part of Netkit, a network emulation environment based on
#     the integration of several existing pieces of software.
#     For more information: http://www.netkit.org/
#
#     Copyright (C) 2015
#         Massimo Rimondini (rimondin@ing.uniroma3.it)
#     Computer Networks Research Group, Roma Tre University
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, version 3 of the License.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /opt/netkit-setup/utils.sh

becho "Installing extra packages"

apt-get update

# Pre-configure package options to avoid interactive requests
/usr/bin/debconf-set-selections < /netkit-fs-debconf
rm /netkit-fs-debconf

# First pass: install most packages
cat <<EOF | sed 's/#.*$//' | grep -v "^ *$" | xargs apt-get install -y

# SDN-related tools
openvswitch-switch
python-ryu
ryu-bin

# Packet filtering and DPI
arptables
ebtables
ipset
iptables
nftables
shorewall
shorewall6
snort

# DNS
bind9
pdns-server
pdns-recursor

# Routing
bird
mrd6
quagga
xorp

# Servers and daemons
apache2
exim4
exim4-daemon-heavy
freeradius
haproxy
isc-dhcp-server
nfs-kernel-server
openssh-server
proftpd-basic
radvd
rinetd
samba
snmpd
spamassassin
squid3
tcpd
telnetd
tftpd

# Sniffers
dsniff
ssldump
tcpdump
tshark

# Connectivity (tunnels, VPNs, VLANs)
httptunnel
openvpn
ppp
vlan

# Generic network utilities
alpine
arping
bind9-host
bridge-utils
curl
dhcpcd5
dnsutils
ftp
ifenslave
ipcalc
ipsec-tools
iputils-tracepath
ipv6calc
links
lynx
mrtg
mtr-tiny
mutt
ncftp
netcat-openbsd
nfs-common
nmap
openssh-client
paris-traceroute
procmail
smbclient
snmp
strongswan
strongswan-charon
tcpreen
tcpreplay
tcpslice
tcptraceroute
telnet
tftp
wget

# Miscellaneous utilities
apt-file
aptitude
bash-completion
cpio
daemon
debconf-utils  # Required to obtain debconf-get-selections
dialog
ed
emacs
expect
file
gawk
gnupg
hping3
htop
imagemagick
info
ipvsadm
locate
lsb-release
lsof
mc
minicom
mktemp
netexpect
openssl
patch
psmisc
python-scapy
python3
rlwrap
screen
sendip
socat
strace
sudo
tmux
uml-utilities
vacation
vim

EOF


# Second pass: stop conflicting services (i.e., those for which
# multiple alternative daemons are about to be installed) and install
# additional packages whose setup scripts are expected to fail
# (note: this requires using `|| true' because bash would abort
# script execution otherwise)
while read SERVICE; do
   systemctl stop $SERVICE || true
done <<EOF
bind9
pdnsd
EOF

cat <<EOF | sed 's/#.*$//' | grep -v "^ *$" | xargs apt-get install -y || true
dnsmasq # Requires stopping bind9 before being installed
isc-dhcp-client # Installation scripts fail because they attempt to start the service without any configured interfaces to listen on, and because the only available interface is of type "Serial Line IP", not Ethernet
pimd # Expected to fail because of the lack of configured vifs
EOF

becho "Refreshing list of package files"
apt-file update

