#!/bin/sh

#     This script is part of Netkit, a network emulation environment based on
#     the integration of several existing pieces of software.
#     For more information: http://www.netkit.org/
#
#     Copyright (C) 2015
#         Massimo Rimondini (rimondin@ing.uniroma3.it)
#     Computer Networks Research Group, Roma Tre University
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, version 3 of the License.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /opt/netkit-setup/utils.sh

becho "Configuring installed packages"

# Disable boot-time services
while read SERVICENAME; do
systemctl disable $SERVICENAME
done << EOF
apache2
bind9
cron
dhcpcd
dnsmasq
ebtables
exim4
freeradius
haproxy
inetd
ipvsadm
isc-dhcp-server
mrd6
nfs-common
nfs-kernel-server
nmbd
openvpn
openvswitch-switch
pdns
pdnsd
pdns-recursor
pimd
polkitd
pppd-dns
proftpd
quagga
radvd
rinetd
rpcbind
rsyslog
samba-ad-dc
setkey
shorewall
shorewall6
smbd
snmpd
snort
spamassassin
squid3
ssh
strongswan
systemd-timesyncd
uml-utilities
uuidd
xorp
cryptsetup.target
graphical.target
mail-transport-agent.target
nss-lookup.target
swap.target
EOF

becho "Creating convenient symbolic links to support old service names"
# Remember to update the old-services-wrapper.sh script every time
# changes are made to the following list.
while read SERVICENAME; do
ln -s /etc/systemd/netkit/old-services-wrapper.sh /etc/init.d/$SERVICENAME
done <<EOF
zebra
bind
EOF

becho "Changing shell pointed to by /bin/sh to bash"
ln -fs bash /bin/sh

