#!/bin/sh

#     This script is part of Netkit, a network emulation environment based on
#     the integration of several existing pieces of software.
#     For more information: http://www.netkit.org/
#
#     Copyright (C) 2015
#         Massimo Rimondini (rimondin@ing.uniroma3.it)
#     Computer Networks Research Group, Roma Tre University
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, version 3 of the License.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /opt/netkit-setup/utils.sh

becho "Enabling forwarding"
sed -i 's/net\.ipv4\.ip_forward/net.ipv4.ip_forward=1/; s/net\.ipv6\.conf\.all\.forwarding/net.ipv6.conf.all.forwarding=1/' /etc/sysctl.conf

becho "Disabling ICMP rate limiting"
echo "net.ipv4.icmp_ratelimit=0" >> /etc/sysctl.conf
echo "net.ipv6.icmp.ratelimit=0" >> /etc/sysctl.conf

becho "Configuring resolv.conf"
cat >/etc/resolv.conf <<EOF
# search default.domain.suffix
# nameserver 10.0.2.3
EOF

