#!/bin/sh

#     This script is part of Netkit, a network emulation environment based on
#     the integration of several existing pieces of software.
#     For more information: http://www.netkit.org/
#
#     Copyright (C) 2015
#         Massimo Rimondini (rimondin@ing.uniroma3.it)
#     Computer Networks Research Group, Roma Tre University
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, version 3 of the License.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /opt/netkit-setup/utils.sh

becho "Setting systemd default target to multi-user (for non-graphical login)"
systemctl set-default multi-user

becho "Enabling boot-time Netkit-specific scripts in virtual machines"
systemctl enable netkit-mount-kernel-modules-dir.service
systemctl enable netkit-mount-host-dirs.service
systemctl enable netkit-get-vm-files.service