#!/bin/sh

#     This script is part of Netkit, a network emulation environment based on
#     the integration of several existing pieces of software.
#     For more information: http://www.netkit.org/
#
#     Copyright (C) 2015
#         Massimo Rimondini (rimondin@ing.uniroma3.it)
#     Computer Networks Research Group, Roma Tre University
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, version 3 of the License.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /opt/netkit-setup/utils.sh

becho "Generating list of installed packages"
mkdir -p /temphost
mount -t hostfs -o rw,/tmp none /temphost
echo "=== INSTALLED PACKAGES ===" > /temphost/netkit-package-list
echo >> /temphost/netkit-package-list
/usr/bin/dpkg-query -W --showformat '${Package;-35}\t${Version} (${Architecture})\t${binary:Summary}\n' | grep -v "^lib" >> /temphost/netkit-package-list
echo >> /temphost/netkit-package-list
echo >> /temphost/netkit-package-list
echo "=== INSTALLED LIBRARIES ===" >> /temphost/netkit-package-list
echo >> /temphost/netkit-package-list
/usr/bin/dpkg-query -W --showformat '${Package;-35}\t${Version} (${Architecture})\t${binary:Summary}\n' | grep "^lib" >> /temphost/netkit-package-list
echo >> /temphost/netkit-package-list
echo >> /temphost/netkit-package-list
umount /temphost
rmdir /temphost

