#!/bin/sh

#     This script is part of Netkit, a network emulation environment based on
#     the integration of several existing pieces of software.
#     For more information: http://www.netkit.org/
#
#     Copyright (C) 2015
#         Massimo Rimondini (rimondin@ing.uniroma3.it)
#     Computer Networks Research Group, Roma Tre University
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, version 3 of the License.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /opt/netkit-setup/utils.sh

becho "Applying quagga-specific tweaks"
sed -i -r '/^zebra=/ s/no/yes/' /etc/quagga/daemons
for SAMPLE_FILE in /usr/share/doc/quagga/examples/*; do ln -s $SAMPLE_FILE /etc/quagga/; done
echo "password zebra" > /etc/quagga/zebra.conf

cat <<"EOF" >>/etc/bash.bashrc
export VTYSH_PAGER=/bin/cat
EOF

