#!/bin/bash

#     This script is invoked by the Netkit filesystem Makefile in order to
#     perform operations inside the filesystem image. Netkit is a network
#     emulation environment based on the integration of several existing pieces
#     of software.  For more information: http://www.netkit.org/
#
#     Copyright (C) 2016  Massimo Rimondini (rimondini@ing.uniroma3.it)
#     Computer Networks Research Group, Roma Tre University
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, version 3 of the License.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Exit if any of the commands below fails (note that this will cause a
# harmless panic in the UML kernel, because it implies killing init).
#set -e

# Extra assignments on the UML kernel command line are
# passed as environment variables to this script.
# Expected variables are:
# TARGETARCH: target architecture for the filesystem image (i386 or x86_64)
# WORKDIR: the directory where the filesystem build is taking place

mount -o remount,rw /
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /run
mount -t devtmpfs none /dev

# Replace resolv.conf in well-known (and writable) locations
for DIR in /run/{NetworkManager,resolvconf}; do
	mkdir ${DIR}
	echo "nameserver 8.8.8.8" > ${DIR}/resolv.conf
done

# Enable network (required by debootstrap to fetch repository information)
echo Setting up network...
ip addr add 10.0.2.15/8 dev eth0
ip link set eth0 up
ip route add default dev eth0

cd ${WORKDIR}

make do-privileged-tasks TARGET_ARCH=${TARGETARCH}

/sbin/poweroff -f

